#!/usr/bin/bash

# Setup guide from
# https://github.com/arch4edu/arch4edu/wiki/Add-arch4edu-to-your-Archlinux

# Install keys
pacman-key --init
pacman-key --recv-keys 7931B6D628C8D3BA
pacman-key --finger 7931B6D628C8D3BA
pacman-key --lsign-key 7931B6D628C8D3BA

# Configure the global server
echo "[arch4edu]" >> /etc/pacman.conf
echo "Server = https://repository.arch4edu.org/\$arch" >> /etc/pacman.conf

# Update cache
pacman -Sy
