name: "Check Arch Linux"
on:
  pull_request:
    paths:
      - 'ci-archlinux.dockerfile'

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make archlinux
