name: "Check CentOS7"
on:
  pull_request:
    paths:
      - 'ci-centos7.dockerfile'
      - 'petsc/**'

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make centos8
