name: "Daily Update"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # preCICE nightly runs at 2am, this one two hours later

jobs:
  latest:
    strategy:
      matrix:
        image: [aste]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          dockerfile: "./ci-${{ matrix.image }}.dockerfile"
          repository: precice/ci-${{ matrix.image }}
          tags: latest
