name: "Check Formatting"
on:
  pull_request:
    paths:
      - 'ci-formatting.dockerfile'

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make formatting
