name: "Monthly Update"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *'

jobs:
  latest:
    strategy:
      fail-fast: false
      matrix:
        image: [archlinux, ubuntu-2004, ubuntu-2204, ubuntu-2404, fedora] # no intel due to runner limitation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          dockerfile: "./ci-${{ matrix.image }}.dockerfile"
          repository: precice/ci-${{ matrix.image }}
          tags: latest
