name: "Check Ubuntu 24.04"
on:
  pull_request:
    paths:
      - 'ci-ubuntu-2404.dockerfile'
      - 'ubuntu/**'

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make ubuntu-2404
