name: "Update Ubuntu 22.04"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'ci-ubuntu-2204.dockerfile'
      - 'ubuntu/**'

jobs:
  latest:
    runs-on: ubuntu-latest
    env:
      image: ubuntu-2204
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          dockerfile: "./ci-${{ env.image }}.dockerfile"
          repository: precice/ci-${{ env.image }}
          tags: latest
