name: "Check Ubuntu 18.04"
on:
  pull_request:
    paths:
      - 'ci-ubuntu-1804.dockerfile'
      - 'petsc/**'
      - 'ubuntu/**'
      - 'eigen3/**'

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ubuntu-1804
